name: Pronto

on:
  pull_request_target:

jobs:
  pronto:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
          bundler-cache: true
      - name: Cache gems
        id: cache-gems
        uses: actions/cache@v2
        with:
          path: gem_cache
          key: ${{ runner.os }}-gems
      - name: Install pronto
        env:
          GEM_HOME: gem_cache
          GEM_PATH: gem_cache
        run: gem install pronto
      - name: Run pronto
        env:
          GEM_HOME: gem_cache
          GEM_PATH: gem_cache
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export PATH=$(pwd)/gem_cache/bin:$PATH
          hub pr checkout ${{ github.event.pull_request.id }}
          git fetch origin ${{ github.event.pull_request.base.ref }}
          PRONTO_PULL_REQUEST_ID=$(cat PULL_REQUEST_NUMBER) \
          PRONTO_GITHUB_ACCESS_TOKEN="${{ github.token }}" \
            pronto run -f github_status github_pr -c origin/${{ github.event.pull_request.base.ref }}
