name: Specs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby-version:
          - "2.3"
          - "2.4"
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
        exclude:
          - ruby-version: "2.3" # Rugged uses the wrong openssl version on CI and segfaults (similar to https://github.com/libgit2/rugged/issues/718)
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@7bcf9e73c0ee77d178e72c0ec69f1a99c1afc1f3 # v2.7.5
        env:
          CC_TEST_REPORTER_ID: 3d676246ffa66d3fdef6253a9870431b1a2da04e9ecb25486c08a38823c37b6a
          COVERAGE: true
        with:
          coverageCommand: bundle exec rspec
      - if: matrix.ruby-version == '2.4' && github.event_name == 'pull_request'
        name: Save pull request information
        run: |
          mkdir -p ./test_artifacts
          echo ${{ github.event.number }} > ./test_artifacts/PULL_REQUEST_NUMBER
          echo ${{ github.event.pull_request.base.ref }} > ./test_artifacts/PULL_REQUEST_TARGET_BRANCH
      - if: matrix.ruby-version == '2.4' && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v2
        with:
          name: test_artifacts
          path: test_artifacts/
